import type { Metadata } from "next";
import "./globals.css";
import { openSans } from "@/utils/fonts"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en-EN">
			<body className={`${openSans.className}`}>
				{children}
			</body>
		</html>
	);
};