import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/utils/fonts"
import Providers from "@/app/providers";
import Footer from "@/components/layout/footer";
import RightBar from "@/components/layout/rightBar";

export const metadata: Metadata = {
	title: "Kqan_ - FullStack Web Developer",
	description: "Generated by create next app",
	authors: [{name: "Kqan", url:"https://kqan1.github.com/"}],
    keywords: [""],
    category: "portfolio",
    generator: "next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en-EN" className="min-h-screen h-full light">
			<body className={`${inter.className} relative text-gray-800 dark:text-gray-200 antialiased bg-neutral-50 dark:bg-black overflow-x-hidden h-full`}>
				<Providers>
					<RightBar />
					<main className="relative flex flex-col min-h-screen">
						<div className="relative flex-grow flex-1 h-full">
                            {children}
                        </div>
						<Footer />
					</main>
				</Providers>
			</body>
		</html>
	);
};